<Project>
	<PropertyGroup>
		<Version>3.1.0</Version>
		<AssemblyVersion>3.1.0</AssemblyVersion>
		<Authors>Stefan Fjällemark</Authors>
		<Company>Tellurian Interactive</Company>
	</PropertyGroup>
	<PropertyGroup>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<CompressionEnabled>false</CompressionEnabled>
	</PropertyGroup>
</Project>