<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Tellurian.WagonCardApp.Shared</RootNamespace>
    <AssemblyName>Tellurian.WagonCardApp.Shared</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Markdig" Version="0.43.0" />
    <PackageReference Include="QRCoder" Version="1.7.0" />
  </ItemGroup>
  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>
</Project>